### ISSUE TITLE
`xgd-open` as a backup for `mimeopen`

### ISSUE THREAD

**Issue by foxyseta** [niuiic/typst-preview.nvim#1]
How about using `xdg-open` as a backup plan for distros that do not ship `mimeopen`? This way less users would need to touch their own plugin config.

**Comment by niuiic** [comment]
Check the `preview` option in configuation

**Comment by foxyseta** [comment]
I already checked that actually. Just thought it could have been useful to have that builtin, sorry.

**Comment by foxyseta** [comment]
Anyway, great plugin!
